recipebox/main/routes.py
from flask import (
	render_template,
	Blueprint,
	request,
	g,
	redirect,
	url_for)
from recipebox.models import Recipe
import os, json, boto3
from recipebox.utils import rand_picture_name
from recipebox.main.forms import SearchForm

main = Blueprint('main', __name__)

@main.before_app_request
def before_app_request():
	g.search_form = SearchForm()

@main.route('/')
@main.route('/home')
def home():
	recipes = Recipe.query.all()
	return render_template("home.html", recipes=recipes)

@main.route('/search')
def search():
	if not g.search_form.validate():
		return redirect(url_for('main.home'))
	recipes = Recipe.query.all()
	return render_template('home.html', title='Search', recipes=recipes)

@main.route('/about')
def about():
	return render_template("about.html", title="About")

@main.route('/sign_s3/')
def sign_s3():
	S3_BUCKET = os.environ.get('S3_BUCKET_NAME')

	file_name = rand_picture_name(request.args.get('file_name'))
	file_type = request.args.get('file_type')

	s3 = boto3.client('s3')

	presigned_post = s3.generate_presigned_post(
		Bucket = S3_BUCKET,
		Key = file_name,
		Fields = {"acl": "public-read", "Content-Type": file_type},
		Conditions = [
			{"acl": "public-read"},
			{"Content-Type": file_type}
		],
		ExpiresIn = 3600
	)

	return json.dumps({
		'data': presigned_post,
		'url': 'https://%s.s3.us-west-1.amazonaws.com/%s' % (S3_BUCKET, file_name)
	})

recipebox/recipes/routes.py
from flask import (
	Blueprint,
	render_template,
	flash,
	redirect,
	url_for,
	abort,
	jsonify,
	request
)
from flask_login import current_user, login_required
from recipebox import db
from recipebox.recipes.forms import CreateRecipeForm, EditRecipeForm
from recipebox.models import Recipe, Comment

recipes = Blueprint('recipes', __name__)

@recipes.route('/recipes/new', methods=['POST', 'GET'])
@login_required
def create_recipe():
	form = CreateRecipeForm()
	if form.validate_on_submit():
		recipe = Recipe(title=form.title.data,
						description=form.description.data,
						cook_time=form.cook_time.data,
						servings=form.servings.data,
						ingredients=form.ingredients.data,
						directions=form.directions.data,
						user_id=current_user.id)
		if form.picture.data and form.picture.data != url_for('static', filename='img/default.png'):
			recipe.image_file = form.picture.data
		db.session.add(recipe)
		db.session.commit()
		flash('Your recipe has been added!', 'success')
		return redirect(url_for('main.home'))
	recipe_picture = url_for('static', filename='img/default.png')
	return render_template('recipes/create_edit_recipe.html',
						title="Create Recipe",
						legend="Add a recipe!",
						recipe_picture=recipe_picture,
						form=form)

@recipes.route('/recipe/<int:recipe_id>')
def recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	return render_template('recipes/recipe.html', title=recipe.title, recipe=recipe)

@recipes.route('/recipe/<int:recipe_id>/comments')
def recipe_comments(recipe_id):
	comments = Comment.query.filter_by(recipe_id=recipe_id).order_by(Comment.date_posted.desc())
	print(comments)
	return jsonify({"comments": [comment.serialize for comment in comments]})

@recipes.route('/recipe/<int:recipe_id>/comments/new', methods=['POST'])
def create_comment(recipe_id):
	args = request.values	
	if not current_user.is_authenticated or "body" not in args:
		return jsonify({'success': False}), 403	
	recipe = Recipe.query.get_or_404(recipe_id)

	comment = Comment(body=args['body'], recipe_id=recipe.id, user_id=current_user.id)
	db.session.add(comment)
	db.session.commit()
	
	return jsonify({'success': True}), 201

@recipes.route('/recipe/<int:recipe_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	if recipe.author != current_user:
		abort(403)
	form = EditRecipeForm(obj=recipe)
	if form.validate_on_submit():
		recipe.title = form.title.data
		recipe.description = form.description.data
		recipe.cook_time = form.cook_time.data
		recipe.servings = form.servings.data
		recipe.ingredients = form.ingredients.data
		recipe.directions = form.directions.data
		if form.picture.data and recipe.image_file != form.picture.data:
			recipe.image_file = form.picture.data
		db.session.commit()
		return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
	recipe_picture = recipe.get_image_url()
	print(recipe_picture)
	return render_template('recipes/create_edit_recipe.html',
						title="Update Recipe",
						legend="Edit recipe!",
						recipe_picture=recipe_picture,
						form=form)
	
@recipes.route('/recipe/<int:recipe_id>/delete', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	if recipe.author != current_user:
		abort(403)
	db.session.delete(recipe)
	db.session.commit()
	flash('Your recipe has been deleted!', 'success')
	return redirect(url_for('main.home'))

recipebox/users/routes.py
from flask import (
	render_template,
	Blueprint,
	redirect,
	url_for,
	flash,
	request,
	jsonify
)
from flask_login import (
	login_user,
	current_user,
	logout_user,
	login_required
)
from recipebox import db
from recipebox.models import User, Recipe
from recipebox.users.forms import (
	RegistrationForm,
	LoginForm,
	UpdateAccountForm,
	UpdatePasswordForm,
	RequestResetForm,
	ResetPasswordForm
)

users = Blueprint('users', __name__)

@users.route('/register', methods=['POST', 'GET'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(
			username=form.username.data,
			email=form.email.data)
		user.set_password(form.password.data)
		db.session.add(user)
		db.session.commit()
		flash(f'Your account has been created. You can now login.',
			'success')
		return redirect(url_for('users.login'))
	return render_template(
		'users/register.html', title="Register", form=form)

@users.route('/login', methods=['POST', 'GET'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and user.check_password(form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		flash('Login unsuccessful. Please check email and password.',
			'danger')
	return render_template(
		'users/login.html', title="Login", form=form)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data \
			and form.picture.data != current_user.image_file:
			current_user.image_file = form.picture.data
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash("Your account has been updated!", 'success')
		return redirect(url_for('users.account'))
	pw_form = UpdatePasswordForm()
	form.username.data = current_user.username
	form.email.data = current_user.email
	profile_pic = current_user.get_image_url()
	return render_template(
		'users/account.html', title='Account',
		form=form, profile_pic=profile_pic, pw_form=pw_form)

@users.route('/stats')
@login_required
def user_stats():
	profile_pic = current_user.get_image_url()
	return render_template(
		'users/stats.html', title='Stats', profile_pic=profile_pic)

@users.route('/update_password', methods=['POST'])
@login_required
def update_password():
	form = UpdatePasswordForm()
	if form.validate_on_submit():
		if current_user.check_password(form.old_password.data):
			current_user.set_password(form.password.data)
			db.session.commit()
			flash('Your password has been updated!', 'success')
			return redirect(url_for('users.account'))
		flash('Your current password does not match. Please try again!',
			'danger')
	return redirect(url_for('users.account'))

@users.route('/users/<int:user_id>/recipes')
def user_recipes(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('home.html',
		title=f"{user.username}'s recipes",
		heading=f"Showing recipes by {user.username}",
		recipes=user.recipes)

@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		user.send_reset_email()
		flash(
			'An email has been sent with instructions to reset your password.',
			'info')
		return redirect(url_for('users.login'))
	return render_template(
		'users/reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('This is an invalid token.', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		user.set_password(form.password.data)
		db.session.commit()
		flash('Your password has been updated!', 'success')
		return redirect(url_for('users.login'))
	return render_template(
		'users/reset_token.html', title='Reset Password', form=form)

@users.route('/made_recipe/')
def made_recipe():
	recipe = Recipe.query.get_or_404(request.args.get('recipe_id'))
	data = {}
	if recipe in current_user.made_recipes:
		current_user.made_recipes.remove(recipe)
		data['added'] = False
	else:
		current_user.made_recipes.append(recipe)
		data['added'] = True

	db.session.commit()
	data['count'] = len(recipe.users)
	return jsonify(data)

recipebox/templates/about.html
{% extends "layout.html" %}
{% block content %}
	<div class="article">
		<h2>About</h2>
		<p>recipe_box is a place for you to share and find new recipes, but it's mostly here so I can practice my programming skills. This is a work in progress, so things may change from time to time. View the Github page for this site <a href="https://github.com/Hall-Erik/recipe_box">here</a>.</p>
		<p>Feel free to <a href="{{ url_for('users.register') }}">create an account</a> and start sharing.</p>
	</div>
{% endblock content %}

recipebox/templates/home.html
{% extends "layout.html" %}
{% block content %}
	{% if heading %}
		<h5>{{ heading }}</h5>
	{% endif %}
	<div class="row">
	{% for recipe in recipes %}
		<div class="col-xs-12 col-sm-6 col-md-3 mb-1">
			<div class="card h-100">
				<div class="card-img-top home-recipe-pic-div">
					<a href="{{ url_for('recipes.recipe', recipe_id=recipe.id )}}">
						<img class="home-recipe-pic" src="{{ recipe.get_image_url() }}" />
					</a>
				</div>
				<div class="card-body">					
					<h4 class="card-title"><a href="{{ url_for('recipes.recipe', recipe_id=recipe.id )}}">{{ recipe.title }}</a></h4>
					<small class="card-text text-muted">
						Author: <a href="{{ url_for('users.user_recipes', user_id=recipe.author.id) }}">{{ recipe.author.username }}</a>
					</small>
					<p class="card-text">{{ recipe.description }}</p>
				</div>
			</div>
		</div>
	{% endfor %}
	</div>
{% endblock content%}

recipebox/templates/img_scripts.html
<script>
  var sign_s3_url = "{{ url_for('main.sign_s3') }}";
</script>
<script src="{{ url_for('static', filename='js/load-image.all.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/upload_image.js') }}"></script>

recipebox/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>recipe_box - {{ title }}</title>
    {% else %}
        <title>recipe_box</title>
    {% endif %}

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">recipe_box</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- <div class="navbar-nav navbar-left ml-auto mr-auto">
              <form class="navbar-form" method="GET"
                  action="{{ url_for('main.search') }}">
                {{ g.search_form.q(size=30, class='form-control',
                  placeholder=g.search_form.q.label.text) }}
              </form>
            </div> -->
            <!-- Navbar Right Side -->
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
	                <a class="nav-item nav-link" href="{{ url_for('recipes.create_recipe') }}">New Recipe</a>
                  <div class="dropdown show">
                    <a class="nav-item nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ current_user.username }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                      <a class="dropdown-item" href="{{ url_for('users.user_stats') }}">User Stats</a>
	                    <a class="dropdown-item" href="{{ url_for('users.account') }}">Account Settings</a>
	                    <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
                    </div>
                  </div>
	            {% else %}
                	<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                	<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            	{% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </div>
      </div>  
      {% block content %}{% endblock %}
    </main>

    <!-- Optional JavaScript -->
    <!-- PopperJS and Bootstrap -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>