recipebox/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, TextAreaField, SubmitField, IntegerField,
					HiddenField)
from wtforms.validators import DataRequired, Regexp

class RecipeForm(FlaskForm):
	title = StringField('Name', validators=[DataRequired()])
	description = StringField('Description')
	cook_time = IntegerField('Cook Time', validators=[DataRequired()])
	servings = StringField('Number of Servings',
						validators=[DataRequired(), Regexp(r'(^\d+$)|(^[\d]+-[\d]+$)')])
	picture = HiddenField('Recipe Photo')
	ingredients = TextAreaField('Ingredients')
	directions = TextAreaField('Directions')

class CreateRecipeForm(RecipeForm):	
	submit = SubmitField('Create')

class EditRecipeForm(RecipeForm):
	submit = SubmitField('Update')

recipebox/recipes/routes.py
from flask import (
	Blueprint,
	render_template,
	flash,
	redirect,
	url_for,
	abort,
	jsonify,
	request
)
from flask_login import current_user, login_required
from recipebox import db
from recipebox.recipes.forms import CreateRecipeForm, EditRecipeForm
from recipebox.models import Recipe, Comment

recipes = Blueprint('recipes', __name__)

@recipes.route('/recipes/new', methods=['POST', 'GET'])
@login_required
def create_recipe():
	form = CreateRecipeForm()
	if form.validate_on_submit():
		recipe = Recipe(title=form.title.data,
						description=form.description.data,
						cook_time=form.cook_time.data,
						servings=form.servings.data,
						ingredients=form.ingredients.data,
						directions=form.directions.data,
						user_id=current_user.id)
		if form.picture.data and form.picture.data != url_for('static', filename='img/default.png'):
			recipe.image_file = form.picture.data
		db.session.add(recipe)
		db.session.commit()
		flash('Your recipe has been added!', 'success')
		return redirect(url_for('main.home'))
	recipe_picture = url_for('static', filename='img/default.png')
	return render_template('recipes/create_edit_recipe.html',
						title="Create Recipe",
						legend="Add a recipe!",
						recipe_picture=recipe_picture,
						form=form)

@recipes.route('/recipe/<int:recipe_id>')
def recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	return render_template('recipes/recipe.html', title=recipe.title, recipe=recipe)

@recipes.route('/recipe/<int:recipe_id>/comments')
def recipe_comments(recipe_id):
	comments = Comment.query.filter_by(recipe_id=recipe_id).order_by(Comment.date_posted.desc())
	print(comments)
	return jsonify({"comments": [comment.serialize for comment in comments]})

@recipes.route('/recipe/<int:recipe_id>/comments/new', methods=['POST'])
def create_comment(recipe_id):
	args = request.values	
	if not current_user.is_authenticated or "body" not in args:
		return jsonify({'success': False}), 403	
	recipe = Recipe.query.get_or_404(recipe_id)

	comment = Comment(body=args['body'], recipe_id=recipe.id, user_id=current_user.id)
	db.session.add(comment)
	db.session.commit()
	
	return jsonify({'success': True}), 201

@recipes.route('/recipe/<int:recipe_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	if recipe.author != current_user:
		abort(403)
	form = EditRecipeForm(obj=recipe)
	if form.validate_on_submit():
		recipe.title = form.title.data
		recipe.description = form.description.data
		recipe.cook_time = form.cook_time.data
		recipe.servings = form.servings.data
		recipe.ingredients = form.ingredients.data
		recipe.directions = form.directions.data
		if form.picture.data and recipe.image_file != form.picture.data:
			recipe.image_file = form.picture.data
		db.session.commit()
		return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
	recipe_picture = recipe.get_image_url()
	print(recipe_picture)
	return render_template('recipes/create_edit_recipe.html',
						title="Update Recipe",
						legend="Edit recipe!",
						recipe_picture=recipe_picture,
						form=form)
	
@recipes.route('/recipe/<int:recipe_id>/delete', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	if recipe.author != current_user:
		abort(403)
	db.session.delete(recipe)
	db.session.commit()
	flash('Your recipe has been deleted!', 'success')
	return redirect(url_for('main.home'))

recipebox/users/routes.py
from flask import (
	render_template,
	Blueprint,
	redirect,
	url_for,
	flash,
	request,
	jsonify
)
from flask_login import (
	login_user,
	current_user,
	logout_user,
	login_required
)
from recipebox import db
from recipebox.models import User, Recipe
from recipebox.users.forms import (
	RegistrationForm,
	LoginForm,
	UpdateAccountForm,
	UpdatePasswordForm,
	RequestResetForm,
	ResetPasswordForm
)

users = Blueprint('users', __name__)

@users.route('/register', methods=['POST', 'GET'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(
			username=form.username.data,
			email=form.email.data)
		user.set_password(form.password.data)
		db.session.add(user)
		db.session.commit()
		flash(f'Your account has been created. You can now login.',
			'success')
		return redirect(url_for('users.login'))
	return render_template(
		'users/register.html', title="Register", form=form)

@users.route('/login', methods=['POST', 'GET'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and user.check_password(form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		flash('Login unsuccessful. Please check email and password.',
			'danger')
	return render_template(
		'users/login.html', title="Login", form=form)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data \
			and form.picture.data != current_user.image_file:
			current_user.image_file = form.picture.data
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash("Your account has been updated!", 'success')
		return redirect(url_for('users.account'))
	pw_form = UpdatePasswordForm()
	form.username.data = current_user.username
	form.email.data = current_user.email
	profile_pic = current_user.get_image_url()
	return render_template(
		'users/account.html', title='Account',
		form=form, profile_pic=profile_pic, pw_form=pw_form)

@users.route('/stats')
@login_required
def user_stats():
	profile_pic = current_user.get_image_url()
	return render_template(
		'users/stats.html', title='Stats', profile_pic=profile_pic)

@users.route('/update_password', methods=['POST'])
@login_required
def update_password():
	form = UpdatePasswordForm()
	if form.validate_on_submit():
		if current_user.check_password(form.old_password.data):
			current_user.set_password(form.password.data)
			db.session.commit()
			flash('Your password has been updated!', 'success')
			return redirect(url_for('users.account'))
		flash('Your current password does not match. Please try again!',
			'danger')
	return redirect(url_for('users.account'))

@users.route('/users/<int:user_id>/recipes')
def user_recipes(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('home.html',
		title=f"{user.username}'s recipes",
		heading=f"Showing recipes by {user.username}",
		recipes=user.recipes)

@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		user.send_reset_email()
		flash(
			'An email has been sent with instructions to reset your password.',
			'info')
		return redirect(url_for('users.login'))
	return render_template(
		'users/reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('This is an invalid token.', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		user.set_password(form.password.data)
		db.session.commit()
		flash('Your password has been updated!', 'success')
		return redirect(url_for('users.login'))
	return render_template(
		'users/reset_token.html', title='Reset Password', form=form)

@users.route('/made_recipe/')
def made_recipe():
	recipe = Recipe.query.get_or_404(request.args.get('recipe_id'))
	data = {}
	if recipe in current_user.made_recipes:
		current_user.made_recipes.remove(recipe)
		data['added'] = False
	else:
		current_user.made_recipes.append(recipe)
		data['added'] = True

	db.session.commit()
	data['count'] = len(recipe.users)
	return jsonify(data)

recipebox/templates/recipes/create_edit_recipe.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.csrf_token }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">{{ legend }}</legend>
				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.description.label(class="form-control-label") }}
					{% if form.description.errors %}
						{{ form.description(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.description.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.description(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-row">
					<div class="col-5">
						<div class="form-group">
							{{ form.picture.label }}<br>
							{{ form.picture(id="image_url", value=recipe_picture) }}
							<input class="mb-1" type="file" accept="image/*" id="file_input"/>
							<div id="progress" class="d-none">
  								<div id="progress-bar" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
							</div>
							<img id="preview" class="recipe-pic" src="{{ recipe_picture }}"/>
						</div>
					</div>
					<div class="col-7">
						<div class="form-group">
							{{ form.cook_time.label(class="form-control-label") }}
							{% if form.cook_time.errors %}
								{{ form.cook_time(class="form-control form-control-lg is-invalid", placeholder='minutes')}}
								<div class="invalid-feedback">
									{% for error in form.cook_time.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>	
							{% else %}
								{{ form.cook_time(class="form-control form-control-lg", placeholder='minutes') }}
							{% endif %}
						</div>
						<div class="form-group">
							{{ form.servings.label(class="form-control-label") }}
							{% if form.servings.errors %}
								{{ form.servings(class="form-control form-control-lg is-invalid", placeholder='5, 7-8')}}
								<div class="invalid-feedback">
									{% for error in form.servings.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>	
							{% else %}
								{{ form.servings(class="form-control form-control-lg", placeholder='5, 7-8') }}
							{% endif %}
						</div>
					</div>
				</div>
				<div class="form-group float-none">
					{{ form.ingredients.label(class="form-control-label") }}
					{% if form.ingredients.errors %}
						{{ form.ingredients(class="form-control form-control-lg is-invalid", placeholder='enter each ingredient on a new line...')}}
						<div class="invalid-feedback">
							{% for error in form.ingredients.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.ingredients(class="form-control form-control-lg", placeholder='enter each ingredient on a new line...') }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.directions.label(class="form-control-label") }}
					{% if form.directions.errors %}
						{{ form.directions(class="form-control form-control-lg is-invalid", placeholder='enter each direction on a new line...')}}
						<div class="invalid-feedback">
							{% for error in form.directions.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.directions(class="form-control form-control-lg", placeholder='enter each direction on a new line...') }}
					{% endif %}
				</div>					
			</fieldset>						
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>		
	</div>
	{% include 'img_scripts.html' %}
{% endblock content %}

recipebox/templates/recipes/edit_recipe.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Edit recipe!</legend>
				<div class="form-group">
					{{ form.title.label(class="form-control-label") }}
					{% if form.title.errors %}
						{{ form.title(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.title.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.title(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.description.label(class="form-control-label") }}

					{% if form.description.errors %}
						{{ form.description(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.description.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.description(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.picture.label }}
					{{ form.picture(class="form-control-file")}}
					{% if form.picture.errors %}
							{% for error in form.picture.errors %}
								<span class="text-danger">{{ error }}</span><br />
							{% endfor %}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.cook_time.label(class="form-control-label") }}

					{% if form.cook_time.errors %}
						{{ form.cook_time(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.cook_time.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.cook_time(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.servings.label(class="form-control-label") }}

					{% if form.servings.errors %}
						{{ form.servings(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.servings.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.servings(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.ingredients.label(class="form-control-label") }}

					{% if form.ingredients.errors %}
						{{ form.ingredients(class="form-control form-control-lg is-invalid", placeholder='enter each ingredient on a new line...')}}
						<div class="invalid-feedback">
							{% for error in form.ingredients.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.ingredients(class="form-control form-control-lg", placeholder='enter each ingredient on a new line...') }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.directions.label(class="form-control-label") }}

					{% if form.directions.errors %}
						{{ form.directions(class="form-control form-control-lg is-invalid", placeholder='enter each direction on a new line...')}}
						<div class="invalid-feedback">
							{% for error in form.directions.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.directions(class="form-control form-control-lg", placeholder='enter each direction on a new line...') }}
					{% endif %}
				</div>
			</fieldset>	
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>		
	</div>
{% endblock content %}

recipebox/templates/recipes/recipe.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<div class="d-flex flex-wrap">
			<div class="mr-auto p-2 bd-highlight">
				<h2>{{ recipe.title }}</h2>
			</div>
			{% if recipe.author == current_user %}
			<div class="p-2 bd-highlight">
				<a class="btn btn-outline-info" href="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}">Edit</a>
				<button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
			</div>
			{% endif %}
		</div>
		<div class="row">
			<div class="col-sm-12 col-md-3">
				<img class="recipe-pic" src="{{ recipe.get_image_url() }}" />
			</div>
			<div class="col-sm-12 col-md-9">
				<div class="row">
					<small class="text-muted">User: <a href="{{ url_for('users.user_recipes', user_id=recipe.author.id) }}">{{ recipe.author.username }}</a> | Cook time: {% if recipe.cook_time %}{{ recipe.cook_time }}{% else %}?{% endif %} minutes | Serves: {% if recipe.servings %}{{ recipe.servings }}{% else %}?{% endif%}
					</small>
				</div>
				<div class="row">
					<p>{{ recipe.description }}</p>
				</div>
			</div>
		</div>
		{% if current_user.is_authenticated %}
		<div class="row mt-2">
			<div>
				{% if current_user.made_this(recipe) %}
					<input type="button" id="made-it" class="btn btn-outline-success" value="✓ Made it. {{ recipe.users|length }}" />
				{% else %}
					<input type="button" id="made-it" class="btn btn-success" value="Made it? {{ recipe.users|length }}" />
				{% endif %}
			</div>
			<div class="ml-1"></div>
		</div>
		{% endif %}
		<div class="row">
		{% if recipe.ingredients %}
		<div class="col-sm-12 col-md-4">
			<div class="row">
				<h3>Ingredients</h3>
			</div>
			<div class="row">
				<ul>
					{% set ingredients = recipe.ingredients.split('\r\n') %}
					{% for ingredient in ingredients %}
					<li>{{ ingredient }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>	
		{% endif %}		
		{% if recipe.directions %}
		<div class="col-sm-12 col-md-8">
			<div class="row">			
				<h3>Directions</h3>
			</div>	
			<div class="row">
				<ol>
					{% set directions = recipe.directions.split('\r\n') %}
					{% for direction in directions %}
					<li>{{ direction }}</li>
					{% endfor %}
				</ol>
			</div>
			</div>
		{% endif %}
		</div>
	</div>

	<!-- Comments -->
	<div class="content-section">
		<h3>Comments</h3>
		{% if current_user.is_authenticated %}
			<div class="form-group">
				<textarea class="md-textarea form-control" id="comment" name="comment" rows="3"></textarea>
				<input class="btn btn-primary mt-1" type="button" id="submit-comment" value="Submit">
			</div>
		{% else %}
			<div class="alert alert-dark" role="alert">
				<h5>Log in to post comments.</h5>
			</div>
		{% endif %}
		<div id="comment-section"></div>
	</div>

    <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
  	(function() {
  		var button = document.getElementById('made-it');
			if (button != null) {
  			button.onclick = cahnge_made_recipe;
			}

			get_comments(update_comments);

			var comment_button = document.getElementById("submit-comment");
			comment_button.onclick = function() {
				post_comment();
			}
  	})();

		function post_comment() {
			comment_input = document.getElementById("comment");
			if (comment_input.value != "") {
				var xhr = new XMLHttpRequest();
				var url = "{{ url_for('recipes.create_comment', recipe_id=recipe.id) }}";
				var params = 'body=' + comment_input.value;
				xhr.open("POST", url, true);
				xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
				xhr.onreadystatechange = function(){
					if(xhr.readyState === 4 && xhr.status === 201) {
						get_comments(update_comments);
						comment_input.value = "";
					}
				};
				xhr.send(params);
			}
		}

		// get comments from the server (just dummy data now)
		// need a post_comment func
		function get_comments(callback) {
			var xhr = new XMLHttpRequest();
  		xhr.open("GET", "{{ url_for('recipes.recipe_comments', recipe_id=recipe.id) }}");
  		xhr.onreadystatechange = function(){
				if(xhr.readyState === 4){
					if(xhr.status === 200){
						callback(JSON.parse(xhr.responseText));
					}
				}
			};
			xhr.send();
		}

		// clears and appends to the comment section
		// {comments: [{body, date_posted, author: {name, image}}]}
		function update_comments(response) {
			comment_section = document.getElementById("comment-section");
			while (comment_section.firstChild) {
				comment_section.removeChild(comment_section.firstChild);
			}

			response.comments.forEach(comment => {
				append_comment(comment);
			});
		}

		// append a single comment to the comments section
		function append_comment(comment) {
			comment_section = document.getElementById("comment-section");

			comment_div = document.createElement("div");
			comment_div.className = "media mb-3"
			comment_section.appendChild(comment_div);

			author_img = document.createElement("img");
			author_img.src = comment.author.image;
			author_img.className = "mr-3 comment-profile";
			comment_div.appendChild(author_img);

			media_body = document.createElement("div");
			media_body.className = "media-body";
			comment_div.appendChild(media_body);

			date_div = document.createElement("div");
			date_div.className = "text-muted";
			media_body.appendChild(date_div);

			date_text = document.createTextNode(comment.author.name + " on " + comment.date_posted);
			date_div.appendChild(date_text);

			comment_text = document.createTextNode(comment.body);
			media_body.appendChild(comment_text);
		}

		// Update the "made-it" button when user clicks
		// called by change_made_recipe()
  	function update_button(data) {
  		var button = document.getElementById('made-it');
  		if (data.added) {
			button.className = 'btn btn-outline-success';
			button.value = '✓ Made it. ' + data.count;
  		}
  		else {
			button.className = 'btn btn-success';
			button.value = 'Made it? ' + data.count;
  		}
  	}

		// Send request to server to toggle user's "made-it" status for recipe
  	function cahnge_made_recipe() {
  		var xhr = new XMLHttpRequest();
  		xhr.open("GET", "{{ url_for('users.made_recipe', recipe_id=recipe.id) }}");
  		xhr.onreadystatechange = function(){
				if(xhr.readyState === 4){
					if(xhr.status === 200){
						update_button(JSON.parse(xhr.responseText));
					}
				}
			};
			xhr.send();
  	}
  </script>
{% endblock content %}