recipebox/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField, HiddenField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from recipebox.models import User

class RegistrationForm(FlaskForm):
	username = StringField('Username',
							validators=[DataRequired(), Length(max=20)])
	email = StringField('Email',
							validators=[DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password',
							validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Sign Up')

	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('That username already exists. Please try another.')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('There is already a user associated with that email. Please try again.')

class LoginForm(FlaskForm):
	email = StringField('Email',
							validators=[DataRequired(), Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	remember = BooleanField('Remember Me')
	submit = SubmitField('Sign In')

class UpdateAccountForm(FlaskForm):
	username = StringField('Username',
							validators=[DataRequired(), Length(max=20)])
	email = StringField('Email', validators=[DataRequired(), Email()])
	picture = HiddenField()
	submit = SubmitField('Update Account')

	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user and user != current_user:
			raise ValidationError('That username already exists. Please try another.')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user and user != current_user:
			raise ValidationError('There is already a user associated with that email. Please try again.')

class UpdatePasswordForm(FlaskForm):
	old_password = PasswordField('Current Password', validators=[DataRequired()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password',
							validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Change Password')

class RequestResetForm(FlaskForm):
	email = StringField('Email', validators=[DataRequired(), Email()])
	submit = SubmitField('Request Password Reset')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user is None:
			raise ValidationError('There is no email associated with that email.')

class ResetPasswordForm(FlaskForm):
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password',
							validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Change Password')

recipebox/recipes/routes.py
from flask import (
	Blueprint,
	render_template,
	flash,
	redirect,
	url_for,
	abort,
	jsonify,
	request
)
from flask_login import current_user, login_required
from recipebox import db
from recipebox.recipes.forms import CreateRecipeForm, EditRecipeForm
from recipebox.models import Recipe, Comment

recipes = Blueprint('recipes', __name__)

@recipes.route('/recipes/new', methods=['POST', 'GET'])
@login_required
def create_recipe():
	form = CreateRecipeForm()
	if form.validate_on_submit():
		recipe = Recipe(title=form.title.data,
						description=form.description.data,
						cook_time=form.cook_time.data,
						servings=form.servings.data,
						ingredients=form.ingredients.data,
						directions=form.directions.data,
						user_id=current_user.id)
		if form.picture.data and form.picture.data != url_for('static', filename='img/default.png'):
			recipe.image_file = form.picture.data
		db.session.add(recipe)
		db.session.commit()
		flash('Your recipe has been added!', 'success')
		return redirect(url_for('main.home'))
	recipe_picture = url_for('static', filename='img/default.png')
	return render_template('recipes/create_edit_recipe.html',
						title="Create Recipe",
						legend="Add a recipe!",
						recipe_picture=recipe_picture,
						form=form)

@recipes.route('/recipe/<int:recipe_id>')
def recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	return render_template('recipes/recipe.html', title=recipe.title, recipe=recipe)

@recipes.route('/recipe/<int:recipe_id>/comments')
def recipe_comments(recipe_id):
	comments = Comment.query.filter_by(recipe_id=recipe_id).order_by(Comment.date_posted.desc())
	print(comments)
	return jsonify({"comments": [comment.serialize for comment in comments]})

@recipes.route('/recipe/<int:recipe_id>/comments/new', methods=['POST'])
def create_comment(recipe_id):
	args = request.values	
	if not current_user.is_authenticated or "body" not in args:
		return jsonify({'success': False}), 403	
	recipe = Recipe.query.get_or_404(recipe_id)

	comment = Comment(body=args['body'], recipe_id=recipe.id, user_id=current_user.id)
	db.session.add(comment)
	db.session.commit()
	
	return jsonify({'success': True}), 201

@recipes.route('/recipe/<int:recipe_id>/edit', methods=['POST', 'GET'])
@login_required
def edit_recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	if recipe.author != current_user:
		abort(403)
	form = EditRecipeForm(obj=recipe)
	if form.validate_on_submit():
		recipe.title = form.title.data
		recipe.description = form.description.data
		recipe.cook_time = form.cook_time.data
		recipe.servings = form.servings.data
		recipe.ingredients = form.ingredients.data
		recipe.directions = form.directions.data
		if form.picture.data and recipe.image_file != form.picture.data:
			recipe.image_file = form.picture.data
		db.session.commit()
		return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
	recipe_picture = recipe.get_image_url()
	print(recipe_picture)
	return render_template('recipes/create_edit_recipe.html',
						title="Update Recipe",
						legend="Edit recipe!",
						recipe_picture=recipe_picture,
						form=form)
	
@recipes.route('/recipe/<int:recipe_id>/delete', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
	recipe = Recipe.query.get_or_404(recipe_id)
	if recipe.author != current_user:
		abort(403)
	db.session.delete(recipe)
	db.session.commit()
	flash('Your recipe has been deleted!', 'success')
	return redirect(url_for('main.home'))

recipebox/users/routes.py
from flask import (
	render_template,
	Blueprint,
	redirect,
	url_for,
	flash,
	request,
	jsonify
)
from flask_login import (
	login_user,
	current_user,
	logout_user,
	login_required
)
from recipebox import db
from recipebox.models import User, Recipe
from recipebox.users.forms import (
	RegistrationForm,
	LoginForm,
	UpdateAccountForm,
	UpdatePasswordForm,
	RequestResetForm,
	ResetPasswordForm
)

users = Blueprint('users', __name__)

@users.route('/register', methods=['POST', 'GET'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		user = User(
			username=form.username.data,
			email=form.email.data)
		user.set_password(form.password.data)
		db.session.add(user)
		db.session.commit()
		flash(f'Your account has been created. You can now login.',
			'success')
		return redirect(url_for('users.login'))
	return render_template(
		'users/register.html', title="Register", form=form)

@users.route('/login', methods=['POST', 'GET'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and user.check_password(form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		flash('Login unsuccessful. Please check email and password.',
			'danger')
	return render_template(
		'users/login.html', title="Login", form=form)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route('/account', methods=['POST', 'GET'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data \
			and form.picture.data != current_user.image_file:
			current_user.image_file = form.picture.data
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash("Your account has been updated!", 'success')
		return redirect(url_for('users.account'))
	pw_form = UpdatePasswordForm()
	form.username.data = current_user.username
	form.email.data = current_user.email
	profile_pic = current_user.get_image_url()
	return render_template(
		'users/account.html', title='Account',
		form=form, profile_pic=profile_pic, pw_form=pw_form)

@users.route('/stats')
@login_required
def user_stats():
	profile_pic = current_user.get_image_url()
	return render_template(
		'users/stats.html', title='Stats', profile_pic=profile_pic)

@users.route('/update_password', methods=['POST'])
@login_required
def update_password():
	form = UpdatePasswordForm()
	if form.validate_on_submit():
		if current_user.check_password(form.old_password.data):
			current_user.set_password(form.password.data)
			db.session.commit()
			flash('Your password has been updated!', 'success')
			return redirect(url_for('users.account'))
		flash('Your current password does not match. Please try again!',
			'danger')
	return redirect(url_for('users.account'))

@users.route('/users/<int:user_id>/recipes')
def user_recipes(user_id):
	user = User.query.get_or_404(user_id)
	return render_template('home.html',
		title=f"{user.username}'s recipes",
		heading=f"Showing recipes by {user.username}",
		recipes=user.recipes)

@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		user.send_reset_email()
		flash(
			'An email has been sent with instructions to reset your password.',
			'info')
		return redirect(url_for('users.login'))
	return render_template(
		'users/reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('This is an invalid token.', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		user.set_password(form.password.data)
		db.session.commit()
		flash('Your password has been updated!', 'success')
		return redirect(url_for('users.login'))
	return render_template(
		'users/reset_token.html', title='Reset Password', form=form)

@users.route('/made_recipe/')
def made_recipe():
	recipe = Recipe.query.get_or_404(request.args.get('recipe_id'))
	data = {}
	if recipe in current_user.made_recipes:
		current_user.made_recipes.remove(recipe)
		data['added'] = False
	else:
		current_user.made_recipes.append(recipe)
		data['added'] = True

	db.session.commit()
	data['count'] = len(recipe.users)
	return jsonify(data)

recipebox/templates/users/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			<fieldset>
				<legend class="border-bottom mb-4">Account Info</legend>
				{{ form.csrf_token }}
				<div class="form-row">
					<div class="col-4">
						<div class="form-group">
							{{ form.picture.label('Profile Picture') }}<br />
							{{ form.picture(id="image_url", value=profile_pic) }}
							<input class="mb-1" type="file" accept="image/*" id="file_input"/>
							<div id="progress" class="d-none">
								<div id="progress-bar" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
							</div>
							<img id="preview" class="img-thumbnail profile-pic" src="{{ profile_pic }}"/>														
						</div>
					</div>					
					<div class="col-8">
						<div class="form-group">
							{{ form.username.label(class="form-control-label") }}
							{% if form.username.errors %}
								{{ form.username(class="form-control form-control-lg is-invalid")}}
								<div class="invalid-feedback">
									{% for error in form.username.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>	
							{% else %}
								{{ form.username(class="form-control form-control-lg") }}
							{% endif %}
						</div>
						<div class="form-group">
							{{ form.email.label(class="form-control-label") }}
							{% if form.email.errors %}
								{{ form.email(class="form-control form-control-lg is-invalid")}}
								<div class="invalid-feedback">
									{% for error in form.email.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>	
							{% else %}
								{{ form.email(class="form-control form-control-lg") }}
							{% endif %}
						</div>							
					</div>
				</div>
				<div class="form-row">
					<div class="col-12">
						<div class="form-group">
							{{ form.submit(class="btn btn-outline-info") }}
						</div>
					</div>
				</div>						
			</fieldset>	
		</form>
		<form method="POST" action="{{ url_for('users.update_password') }}">
			{{ pw_form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Update Password</legend>
				<div class="form-group">
                    {{ pw_form.old_password.label(class="form-control-label") }}
                    {% if pw_form.old_password.errors %}
                        {{ pw_form.old_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in pw_form.old_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ pw_form.old_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
				<div class="form-group">
                    {{ pw_form.password.label(class="form-control-label") }}
                    {% if pw_form.password.errors %}
                        {{ pw_form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in pw_form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ pw_form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ pw_form.confirm_password.label(class="form-control-label") }}
                    {% if pw_form.confirm_password.errors %}
                        {{ pw_form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in pw_form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ pw_form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                	{{ pw_form.submit(class="btn btn-outline-info") }}
            	</div>
            </fieldset>
		</form>		
	</div>
	{% include 'img_scripts.html' %}
{% endblock content %}

recipebox/templates/users/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Sign In!</legend>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
			</fieldset>	
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
				<small class="text-muted">
					<a class="ml-2" href="{{ url_for('users.reset_request') }}">Forget your password?</a>
				</small>
			</div>			
		</form>		
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a>
		</small>
	</div>
{% endblock content %}

recipebox/templates/users/register.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Join Today!</legend>
				<div class="form-group">
					{{ form.username.label(class="form-control-label") }}

					{% if form.username.errors %}
						{{ form.username(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.username.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.email.label(class="form-control-label") }}

					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.password.label(class="form-control-label") }}

					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.confirm_password.label(class="form-control-label") }}

					{% if form.confirm_password.errors %}
						{{ form.confirm_password(class="form-control form-control-lg is-invalid")}}
						<div class="invalid-feedback">
							{% for error in form.confirm_password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>	
					{% else %}
						{{ form.confirm_password(class="form-control form-control-lg") }}
					{% endif %}
				</div>
			</fieldset>	
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>			
		</form>		
	</div>
	<div class="border-top pt-3">
		<small class="text-muted">
			Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
		</small>
	</div>
{% endblock content %}

recipebox/templates/users/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

recipebox/templates/users/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

recipebox/templates/users/stats.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
	<div class="row">
		<div class="media">
			<img class="profile-pic" src="{{ profile_pic }}" alt="profile picture" />
			<div class="media-body ml-1">
				<h5>{{ current_user.username }}</h5>
				<small class="text-muted">{{ current_user.email }}</small>
				<p>
					Shared recipes: {{ current_user.recipes|length }}<br />
					Made recipes: {{ current_user.made_recipes|length }}
				</p>
			</div>
		</div>
	</div>
	<h4>Your recipes</h4>
	<div class="row">
		<table>
			<tbody>
				{% for recipe in current_user.recipes %}
					<tr>
						<td>
							<img class="recipe-pic-sm" src="{{ recipe.get_image_url() }}" />
						</td>
						<td>
							<a href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">{{ recipe.title }}</a>
						</td>
						<td>
							<a class="btn btn-outline-info" href="{{ url_for('recipes.edit_recipe', recipe_id=recipe.id) }}">Edit</a>				
						</td>
						<td>
							<button class="btn btn-outline-danger" data-toggle="modal" data-target="#deleteModal{{ loop.index0 }}">Delete</button>
						</td>
					</tr>					
					<!-- Modal -->
					<div class="modal fade" id="deleteModal{{ loop.index0 }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="deleteModalLabel">Delete Recipe?</h5>
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
									<form action="{{ url_for('recipes.delete_recipe', recipe_id=recipe.id) }}" method="POST">
										<input class="btn btn-danger" type="submit" value="Delete">
									</form>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock content %}